In [1]:
import numpy as np

In [108]:
R = - np.ones([6,6])

In [109]:
print(R)

[[-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.]]


In [110]:
R[4,0] = 0
R[3,1] = 0
R[5,1] = 0
R[3,2] = 0
R[1,3] = 0
R[2,3] = 0
R[4,3] = 0
R[0,4] = 0
R[3,4] = 0
R[5,4] = 0
R[1,5] = 100
R[4,5] = 100
R[5,5] = 100

In [172]:
print(R.shape[0])

6


In [112]:
np.max(R)

100.0

In [181]:
# initialisation
def QLearn(alpha, gamma, R, Q, nbEpoch):
    #process
    taille = Q.shape[0];
    for i in range(0,nbEpoch,1): #boucle pour nbEpoch episodes
        state1 = np.random.randint(0,taille) #etat initial aleatoire
        actualState = state1
        nextState = -1
        #print("Début : ", i)
        while (nextState != taille-1): # boucle jusqu'à atteindre etat final (le dernier)
            #choix de l'etat suivant
            nextState = np.random.randint(0, taille)
            while (R[actualState,nextState] < 0): #on choisit un etat suivant possible, ie valeur positive
                nextState = np.random.randint(0,taille)
            #print(nextState)
            #mise à jour de Q
            Q[actualState, nextState] = Q[actualState, nextState] + alpha*(R[actualState, nextState]+gamma*max(Q[nextState])-Q[actualState, nextState])
            actualState = nextState
        #print("------------------")
    Q = 100/np.max(Q)*Q
    Q = Q.astype(int)
    return Q

alpha = 1
gamma = 0.8
Q = np.zeros([6,6])
nbEpisodes = 3000
Qstar = QLearn(alpha, gamma, R, Q, nbEpisodes)
print(Qstar)


[[  0   0   0   0  80   0]
 [  0   0   0  64   0 100]
 [  0   0   0  64   0   0]
 [  0  80  51   0  80   0]
 [ 64   0   0  64   0 100]
 [  0  80   0   0  80 100]]


In [114]:
# Tour de Hanoï : 27 etats possible représenté par un tripler (a, b, c)
# a représente la position du petit disque, b celle du moyen et c celle du grand
# a, b et c prenne leur valeur entre 0 et 2 (trois tours), l'indice de leur position est 
# identifier par un chiffre entre 0 et 26 avec une écriture en base 3 : a + bx3 + cx3²

In [167]:
ID101 = np.eye(27,27)*101
ID101 = ID101.astype(int)
ID2 = np.eye(27,27) # pour obtenir la matrice avec dernière colonne à 0 par produit matriciel
ID2[26,26] = 0
ID2 = ID2.astype(int)
T = np.zeros([27,27]) #pour obtenir la dernière colonne par pdt mat
T[26,26] = 1
T = T.astype(int)
ONE = np.ones([27,27])
ONE = ONE.astype(int)
# init R
R_Hanoi = - np.ones([27,27])
for i in range(0, 27, 1):
    a = i % 3;
    b = (i % 9) // 3;
    c = i // 9;
    # mise à jour des deux possibilités pour déplacer a (toujours possible car plus petit)
    aa = (a + 1) % 3
    aaa = (a + 2) % 3
    j = aa + 3*b + 9*c
    R_Hanoi[i,j] = 0
    j = aaa + 3*b + 9*c
    R_Hanoi[i,j] = 0
    # mise à jour du déplacement de b si possible
    if (a != b):
        bb = 3 - a - b
        j = a + 3*bb + 9*c
        R_Hanoi[i,j] = 0
    # mise à jour du déplacement de c si possbile
    if ((a == b) and (c !=a) ):
        cc = (2*c + a + b) % 3
        j = a + 3*b + 9*cc
        R_Hanoi[i,j] = 0
# mise à jour dernière colonne avec 100 quand déplacement possible
R_Hanoi = R_Hanoi.dot(ID2) + ((R_Hanoi.dot(T) + ONE).dot(T).dot(ID101) - ONE).dot(T) 
R_Hanoi[26,26] = 100
R_Hanoi = R_Hanoi.astype(int)
print(R_Hanoi)

[[ -1   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0  -1   0  -1  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [  0   0  -1  -1  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1   0   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1   0  -1  -1  -1  -1]
 [ -1  -1   0   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1   0  -1  -1  -1   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1   0  -1  -1  -1  -1   0  -1   0  -1  -1  -1  -1  -1  -1  -1  -1  -1
   -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1  -1  -1   0   0  -1  -1  -1  -1  -1  -1  -1  -1  -1   0
   -1  -1  -1  -1  -1 

In [183]:
alpha_Hanoi = 1
gamma_Hanoi = 0.8
Q_Hanoi = np.zeros([27,27])
nbEpisodes_Hanoi = 3000
Qstar_Hanoi = QLearn(alpha_Hanoi, gamma_Hanoi, R_Hanoi, Q_Hanoi, nbEpisodes_Hanoi)
print(Qstar_Hanoi)


[[  0  20  26   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [ 20   0  26   0   0   0   0  20   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [ 20  20   0   0   0  32   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0   0  40  32  26   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0  32   0  32   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0  51   0   0   0   0]
 [  0   0  26  32  40   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0  32   0   0   0  20  20   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0  20   0   0   0   0  26   0  20   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  26  20   0   0   0   0   0   0   0   0   0  20
    0   0   0   0   0 

In [194]:
#utilisation de la matrice Qstar_Hanoi pour se déplace

In [242]:
Depart = np.zeros([27,27])
Depart[0,0] = 1
vecteurPosition = np.arange(27)

positionInitiale = 0
positionSuivante = 0
matEnCours = Depart
while (positionSuivante != 26):
    print(positionSuivante)
    matSuivante = matEnCours.dot(Qstar_Hanoi)
    #print(matSuivante)
    maxMat = np.max(matSuivante)
    boolMat = (matSuivante >= maxMat)
    nextPosition = boolMat.astype(int)
    #print(nextPosition.transpose())
    matEnCours = (nextPosition.transpose()).dot(nextPosition)
    #print("------------------------")
    #print(matEnCours)
    #print("/////////////////////////////")
    positionSuivante = np.max(vecteurPosition.dot(matEnCours))
print(positionSuivante)

0
2
5
4
22
21
24
26
